language: python
cache: pip

matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'
    # Docker dev image
    - sudo: required
      services:
        - docker
      env:
        - IMAGE_NAME=asia.gcr.io/gcp-akash-287109/django-test
      before_install:
        - pwd
        - ls
        - openssl aes-256-cbc -K $encrypted_0a08b4698b52_key -iv $encrypted_0a08b4698b52_iv -in gcp-akash-287109-41bac7d58115.json.enc -out ~/gcp-akash-287109-41bac7d58115.json -d
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce
      install: []

      before_script:
        - docker pull "${IMAGE_NAME}:develop" || true
      script:
        - docker build --pull --cache-from "${IMAGE_NAME}:develop" --tag "$IMAGE_NAME" .

      before_deploy:
        - cat ~/gcp-akash-287109-41bac7d58115.json | docker login -u _json_key --password-stdin https://asia.gcr.io
        - git_sha="$(git rev-parse --short HEAD)"
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:develop"
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${git_sha}-develop"
      deploy:
        provider: script
        script: docker push "${IMAGE_NAME}:develop" && docker push "${IMAGE_NAME}:${git_sha}-develop"
        on:
          branch: develop
